-- 1. Update Schema to support External Links (Safe to run multiple times)
ALTER TABLE marketplace_listings 
ADD COLUMN IF NOT EXISTS external_link TEXT,
ADD COLUMN IF NOT EXISTS source TEXT CHECK (source IN ('shopee', 'lazada', 'amazon', 'other')),
ADD COLUMN IF NOT EXISTS is_promoted BOOLEAN DEFAULT FALSE;

-- 2. Seed Real Products (Top Shopee/Lazada Thailand Sellers)
INSERT INTO marketplace_listings (title, description, price, currency, category, condition, images, location, status, seller_id, external_link, source, is_promoted)
VALUES
-- BEST SELLING FOOD (Shopee Top 5)
('Pedigree Adult Dog Food - Liver & Veg 20kg', 'Complete nutrition for adult dogs. High quality protein for strong muscles. Best value bulk pack.', 1199, 'THB', 'pet_supplies', 'new', ARRAY['https://images.unsplash.com/photo-1589924691195-41432c84c161?q=80&w=800&auto=format&fit=crop'], 'Shopee Mall', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=pedigree%20dog%20food', 'shopee', true),
('SmartHeart Adult Dog Food - Roast Beef 10kg', 'Enhanced brain function formula. High energy. The #1 budget choice in Thailand.', 689, 'THB', 'pet_supplies', 'new', ARRAY['https://images.unsplash.com/photo-1548802673-380ab8ebc03e?q=80&w=800&auto=format&fit=crop'], 'Official Store', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=smartheart%20dog%20food', 'shopee', true),
('Royal Canin Medium Puppy - 10kg', 'Growth support for medium breed puppies. Immune system support. Veterinary recommended.', 2850, 'THB', 'pet_supplies', 'new', ARRAY['https://images.unsplash.com/photo-1623366302587-b38b1ddaefd9?q=80&w=800&auto=format&fit=crop'], 'Royal Canin Official', 'active', auth.uid(), 'https://shopee.co.th/Royal-Canin-Medium-Puppy-Dog-Food-10kg-i.44760596.1764658392', 'shopee', true),
('Hill''s Science Diet Small Paws 1.5kg', 'Tailored nutrition for small breed dogs. Omega-6 & Vitamin E for beautiful skin & coat.', 850, 'THB', 'pet_supplies', 'new', ARRAY['https://images.unsplash.com/photo-1597843786271-105124152c97?q=80&w=800&auto=format&fit=crop'], 'Hills Official', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=hills%20science%20diet', 'shopee', true),
('Orijen Six Fish Dog Food - 2kg', 'Biologically appropriate. Fresh pilchard, mackerel, hake, flounder, rockfish and sole. Grain-free.', 1950, 'THB', 'pet_supplies', 'new', ARRAY['https://images.unsplash.com/photo-1608408843552-32b005fe430a?q=80&w=800&auto=format&fit=crop'], 'Pet Shop', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=orijen%20dog%20food', 'shopee', true),

-- SMART HOME GADGETS (Trending Tech)
('Xiaomi Smart Pet Fountain 2', '2L Capacity. Ultra-quiet pump. Smart link to Mi Home App. Filter replacement reminders.', 289, 'THB', 'electronics', 'new', ARRAY['https://images.unsplash.com/photo-1582234032488-294b62db441f?q=80&w=800&auto=format&fit=crop'], 'Xiaomi Official', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=xiaomi%20pet%20fountain', 'shopee', true),
('Petkit Eversweet 3 Pro Wireless UVC', 'Wireless pump technology. UVC sterilization. Keeps water fresh for days.', 1290, 'THB', 'electronics', 'new', ARRAY['https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=800&auto=format&fit=crop'], 'PetKit Official', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=petkit%20eversweet%203%20pro', 'shopee', true),
('Xiaomi Smart Pet Feeder', 'Remote control via Mi Home app. Scheduled feeding. Moisture-proof lock.', 2390, 'THB', 'electronics', 'new', ARRAY['https://images.unsplash.com/photo-1599305090598-fe179d501227?q=80&w=800&auto=format&fit=crop'], 'Xiaomi Official', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=xiaomi%20pet%20feeder', 'shopee', true),
('Tractive GPS Dog 4 - Worldwide Tracking', 'Unlimited range GPS tracking. Waterproof. Activity monitoring. Requires subscription.', 2500, 'THB', 'electronics', 'new', ARRAY['https://images.unsplash.com/photo-1601758174609-6a45c3608cc6?q=80&w=800&auto=format&fit=crop'], 'Gadget Store', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=tractive%20gps', 'shopee', true),
('Apple AirTag - 4 Pack', 'Keep track of your pets with the Find My network. Precision finding. Easy setup.', 3390, 'THB', 'electronics', 'new', ARRAY['https://images.unsplash.com/photo-1620600858739-1bc151a2d593?q=80&w=800&auto=format&fit=crop'], 'Apple Authorized', 'active', auth.uid(), 'https://shopee.co.th/Apple-AirTag-4-Pack-i.263530182.8550750395', 'shopee', true),

-- TOYS & ACCESSORIES (High Volume Sellers)
('Smart Interactive Ball (Type-C)', 'Automatic rolling ball with RGB LED lights. Keeps pets entertained while you work.', 259, 'THB', 'hobbies', 'new', ARRAY['https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?q=80&w=800&auto=format&fit=crop'], 'Flash Sale', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=smart%20dog%20ball', 'shopee', false),
('KONG Classic Dog Toy - Large', 'The gold standard of dog toys. Perfect for stuffing with treats. Mentally stimulating.', 490, 'THB', 'hobbies', 'new', ARRAY['https://images.unsplash.com/photo-1576201836106-db1758fd1c97?q=80&w=800&auto=format&fit=crop'], 'Official Store', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=kong%20dog%20toy', 'shopee', true),
('Calming Donut Dog Bed - XXL', 'Anxiety relief. Soft and fluffy faux fur. Machine washable. Perfect for large dogs.', 590, 'THB', 'home', 'new', ARRAY['https://images.unsplash.com/photo-1591946614720-90a587da4a36?q=80&w=800&auto=format&fit=crop'], 'Bedding Shop', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=donut%20dog%20bed', 'shopee', false),
('Tactical K9 Dog Harness', 'Military grade durability. Molle system. Handle for control. Adjustable fit.', 450, 'THB', 'apparel', 'new', ARRAY['https://images.unsplash.com/photo-1558235208-9df5977ba36e?q=80&w=800&auto=format&fit=crop'], 'Overseas', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=tactical%20dog%20harness', 'shopee', false),
('Pet Grooming Glove - Pair', 'Gentle deshedding brush glove. Massage your pet while cleaning. Great for all coats.', 69, 'THB', 'pet_supplies', 'new', ARRAY['https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=800&auto=format&fit=crop'], 'Best Seller', 'active', auth.uid(), 'https://shopee.co.th/search?keyword=pet%20grooming%20glove', 'shopee', true);
